#!/bin/bash

#default settings - can be adjusted in /etc/default/loadwatch.cron
export LOADTHRESH=auto
export SQLTHRESH=25
export MEMTHRESH=80
export SWAPTHRESH=30
export APACHETHRESH=120
export APACHEPORT=80

date=$(date +%Y-%m-%d.%H:%M)
dir=/var/log/loadwatch
checklog=${dir}/check.log
file=${dir}/${date}.txt

source /etc/default/loadwatch

# see /etc/default/loadwatch for configuration

if [[ ${LOADTHRESH} -eq "auto" ]]
then
	LOADTHRESH=$(expr $(/bin/grep -c processor /proc/cpuinfo) / 2 + 7)
fi

load=`cat /proc/loadavg | awk '{print $1}' | awk -F '.' '{print $1}'`

read mem swap <<<$(awk '{
	gsub(":$","",$1); m[$1] = $2
	} END {
		printf "%d ", ((m["MemTotal"]-m["MemFree"]-m["Buffers"]-m["Cached"])/m["MemTotal"])*100;
		printf "%d\n",((m["SwapTotal"]-m["SwapCached"]-m["SwapFree"])/m["SwapTotal"])*100;
	}' /proc/meminfo)

cursql=$(/usr/bin/mysqladmin stat|awk '{print $4}')

histsql=$(/usr/bin/mysql -Bse 'show global status LIKE "Max_used_connections";'|awk '{print $2}')

apacheconn=
if [[ -f /usr/local/cpanel/version ]] ; then
	apacheconn=$(/usr/bin/lynx -dump -width 400 localhost:${APACHEPORT}/whm-server-status |awk '/requests\ currently\ being\ processed,/ {print $1}')
else
	apacheconn=$(netstat -nt|awk 'BEGIN{n=0} $4 ~ /:(443|80)$/ { n++; } END { print n;}')
fi

printf "%s load[%s] mem[%s/%s] mysql[%s/%s] httpd[%s]\n" \
	${date} ${load} ${mem} ${swap} \
	${cursql} ${histsql} ${apacheconn} >> ${checklog}

if [ ${load} -gt ${LOADTHRESH} ] || \
	[ ${mem} -gt ${MEMTHRESH} ] || \
	[ ${swap} -gt ${SWAPTHRESH} ] || \
	[ ${cursql} -gt ${SQLTHRESH} ] || \
	[ ${apacheconn} -gt ${APACHETHRESH} ] ; then

	printf "## %s load[%s] mem[%s/%s] mysql[%s/%s] httpd[%s]\n" \
		${date} ${load} ${mem} ${swap} \
		${cursql} ${histsql} ${apacheconn} >> ${checklog}

	[[ ${load} -gt ${LOADTHRESH} ]] && printf " ## load threshold exceeded\n" >> ${file}
	[[ ${mem} -gt ${MEMTHRESH} ]] && printf " ## mem threshold exceeded\n" >> ${file}
	[[ ${swap} -gt ${SWAPTHRESH} ]] && printf " ## swap threshold exceeded\n" >> ${file}
	[[ ${cursql} -gt ${SQLTHRESH} ]] &&  printf " ## sql threshold exceeded\n" >> ${file}
	[[ ${apacheconn} -gt ${APACHETHRESH} ]] && printf " ## http threshold exceeded\n" >> ${file}

	printf "## server overview\n" >> ${file}
	printf "%s load[%s] mem[%s/%s] mysql[%s/%s] httpd[%s]\n" \
		${date} ${load} ${mem} ${swap} \
		${cursql} ${histsql} ${apacheconn} >> ${file}
	free -m >> ${file}
	uptime >> ${file}

	printf "## system overview\n" >> ${file}
	top -bcn1 >> ${file}
	ps auxf >> ${file}

	printf "## mysql stats\n" >> ${file}
	mysqladmin stat >> ${file}
	mysql -e "show processlist\G" >> ${file}
	# mysql -e "show engine innodb status\G" >> ${file}

	printf "## httpd stats\n" >> ${file}
	/bin/netstat -nut|awk '$4 ~ /:(80|443)/ {gsub(/:[0-9]*$/, "", $5); print $5, $6}'|sort|uniq -c|sort -n|tail -n50 >> ${file}
	if [[ -f /usr/local/cpanel/version ]] ; then
		/usr/bin/lynx -dump -width 400 localhost:${APACHEPORT}/whm-server-status >> ${file} 2>/dev/null
	else
		netstat -nt|awk 'BEGIN{n=0} $4 ~ /:(443|80)$/ { n++; } END { print n;}' >> ${file} 2>/dev/null
	fi

fi
